-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 09:55:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uber
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uber` ;

-- -----------------------------------------------------
-- Schema uber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uber` DEFAULT CHARACTER SET utf8 ;
USE `uber` ;

-- -----------------------------------------------------
-- Table `uber`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Drivers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Licenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT UNSIGNED NOT NULL,
  `exp_date` DATE NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Licenses_Drivers_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Licenses_Drivers`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `uber`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Cars` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model_year` INT UNSIGNED NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Cars_Drivers1_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `uber`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `rate` INT UNSIGNED NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` INT UNSIGNED NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Rides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `distance` INT NOT NULL,
  `pick_up_time` DATETIME NOT NULL,
  `drop_off_time` DATETIME NOT NULL,
  `cost` DOUBLE NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Trips_Drivers1_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_Drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `uber`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `serial_number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Services_Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Services_Cars` (
  `Services_id` INT UNSIGNED NOT NULL,
  `cars_id` INT UNSIGNED NOT NULL,
  `cars_drivers_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `cost` DOUBLE NOT NULL,
  PRIMARY KEY (`Services_id`, `cars_id`, `cars_drivers_id`),
  INDEX `fk_Services_has_Cars_Cars1_idx` (`cars_id` ASC, `cars_drivers_id` ASC) VISIBLE,
  INDEX `fk_Services_has_Cars_Services1_idx` (`Services_id` ASC) VISIBLE,
  CONSTRAINT `fk_Services_has_Cars_Services1`
    FOREIGN KEY (`Services_id`)
    REFERENCES `uber`.`Services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Services_has_Cars_Cars1`
    FOREIGN KEY (`cars_id` , `cars_drivers_id`)
    REFERENCES `uber`.`Cars` (`id` , `drivers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Credit_Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Credit_Cards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `exp_date` DATE NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_Credit_Cards_Users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Credit_Cards_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `uber`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uber`.`Rides_Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uber`.`Rides_Requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `location_start` VARCHAR(45) NOT NULL,
  `location_end` VARCHAR(45) NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `rides_id` INT UNSIGNED NOT NULL,
  `rides_drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `rides_id`, `rides_drivers_id`),
  INDEX `fk_Ride_Request_Users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_Ride_Request_Ride1_idx` (`rides_id` ASC, `rides_drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ride_Request_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `uber`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ride_Request_Ride1`
    FOREIGN KEY (`rides_id` , `rides_drivers_id`)
    REFERENCES `uber`.`Rides` (`id` , `drivers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `uber`.`Drivers`
-- -----------------------------------------------------
START TRANSACTION;
USE `uber`;
INSERT INTO `uber`.`Drivers` (`id`, `name`, `birth_date`, `password`, `phone_number`, `rate`) VALUES (1, 'Facundo', '1998-03-13', 'asd123', 123456, 5);
INSERT INTO `uber`.`Drivers` (`id`, `name`, `birth_date`, `password`, `phone_number`, `rate`) VALUES (2, 'Joe', '1989-01-13', '456dsa', 654897, 4);
INSERT INTO `uber`.`Drivers` (`id`, `name`, `birth_date`, `password`, `phone_number`, `rate`) VALUES (3, 'Denis', '1978-07-10', '789fgb', 456123, 2);
INSERT INTO `uber`.`Drivers` (`id`, `name`, `birth_date`, `password`, `phone_number`, `rate`) VALUES (4, 'Emma', '1994-02-23', 'qwe852', 987654, 5);
INSERT INTO `uber`.`Drivers` (`id`, `name`, `birth_date`, `password`, `phone_number`, `rate`) VALUES (5, 'Charlotte', '1993-05-02', 'fgh741', 741963, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uber`.`Licenses`
-- -----------------------------------------------------
START TRANSACTION;
USE `uber`;
INSERT INTO `uber`.`Licenses` (`id`, `number`, `exp_date`, `drivers_id`) VALUES (1, 6516516, '2023-05-10', 1);
INSERT INTO `uber`.`Licenses` (`id`, `number`, `exp_date`, `drivers_id`) VALUES (2, 4984562, '2027-08-10', 4);
INSERT INTO `uber`.`Licenses` (`id`, `number`, `exp_date`, `drivers_id`) VALUES (3, 6516949, '2027-08-10', 3);
INSERT INTO `uber`.`Licenses` (`id`, `number`, `exp_date`, `drivers_id`) VALUES (4, 3166489, '2023-05-10', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uber`.`Cars`
-- -----------------------------------------------------
START TRANSACTION;
USE `uber`;
INSERT INTO `uber`.`Cars` (`id`, `model`, `color`, `make`, `model_year`, `drivers_id`) VALUES (1, 'Corsa', 'White', 'Chevrolet', 2011, 2);
INSERT INTO `uber`.`Cars` (`id`, `model`, `color`, `make`, `model_year`, `drivers_id`) VALUES (2, 'M3', 'Blue', 'BMW', 2015, 1);
INSERT INTO `uber`.`Cars` (`id`, `model`, `color`, `make`, `model_year`, `drivers_id`) VALUES (3, 'Corolla', 'Black', 'Chevrolet', 2017, 2);
INSERT INTO `uber`.`Cars` (`id`, `model`, `color`, `make`, `model_year`, `drivers_id`) VALUES (4, '208', 'White', 'Peugeot', 2015, 3);
INSERT INTO `uber`.`Cars` (`id`, `model`, `color`, `make`, `model_year`, `drivers_id`) VALUES (5, 'Fiesta', 'Red', 'Ford', 2010, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uber`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `uber`;
INSERT INTO `uber`.`Users` (`id`, `name`, `age`, `rate`, `password`, `phone_number`, `location`) VALUES (1, 'James', 17, 5, '78945qwe', 4654598, 'New York');
INSERT INTO `uber`.`Users` (`id`, `name`, `age`, `rate`, `password`, `phone_number`, `location`) VALUES (2, 'Lucas', 20, 3, '8879vdvfd', 5845631, 'Las Vegas');
INSERT INTO `uber`.`Users` (`id`, `name`, `age`, `rate`, `password`, `phone_number`, `location`) VALUES (3, 'William', 35, 5, 'q12wd56qw', 2315456, 'Los Angeles');
INSERT INTO `uber`.`Users` (`id`, `name`, `age`, `rate`, `password`, `phone_number`, `location`) VALUES (4, 'Benjamin', 50, 4, 'g5g6dfg41', 2315647, 'Los Angeles');
INSERT INTO `uber`.`Users` (`id`, `name`, `age`, `rate`, `password`, `phone_number`, `location`) VALUES (5, 'Judith', 26, 4, 'q13ew213', 8945621, 'Los Angeles');

COMMIT;