-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 03:06:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drivers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Licenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT UNSIGNED NOT NULL,
  `exp_date` DATE NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Licenses_Drivers_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Licenses_Drivers`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `mydb`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model_year` INT UNSIGNED NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Cars_Drivers1_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `mydb`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `rate` INT UNSIGNED NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` INT UNSIGNED NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `distance` INT NOT NULL,
  `pick_up_time` DATETIME NOT NULL,
  `drop_off_time` DATETIME NOT NULL,
  `cost` DOUBLE NOT NULL,
  `drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `drivers_id`),
  INDEX `fk_Trips_Drivers1_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_Drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `mydb`.`Drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `serial_number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services_Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services_Cars` (
  `Services_id` INT UNSIGNED NOT NULL,
  `cars_id` INT UNSIGNED NOT NULL,
  `cars_drivers_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `cost` DOUBLE NOT NULL,
  PRIMARY KEY (`Services_id`, `cars_id`, `cars_drivers_id`),
  INDEX `fk_Services_has_Cars_Cars1_idx` (`cars_id` ASC, `cars_drivers_id` ASC) VISIBLE,
  INDEX `fk_Services_has_Cars_Services1_idx` (`Services_id` ASC) VISIBLE,
  CONSTRAINT `fk_Services_has_Cars_Services1`
    FOREIGN KEY (`Services_id`)
    REFERENCES `mydb`.`Services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Services_has_Cars_Cars1`
    FOREIGN KEY (`cars_id` , `cars_drivers_id`)
    REFERENCES `mydb`.`Cars` (`id` , `drivers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Credit_Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credit_Cards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `exp_date` DATE NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_Credit_Cards_Users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Credit_Cards_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rides_Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rides_Requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `location_start` VARCHAR(45) NOT NULL,
  `location_end` VARCHAR(45) NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `rides_id` INT UNSIGNED NOT NULL,
  `rides_drivers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `rides_id`, `rides_drivers_id`),
  INDEX `fk_Ride_Request_Users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_Ride_Request_Ride1_idx` (`rides_id` ASC, `rides_drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ride_Request_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ride_Request_Ride1`
    FOREIGN KEY (`rides_id` , `rides_drivers_id`)
    REFERENCES `mydb`.`Rides` (`id` , `drivers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
